### ISSUE TITLE
于其他仓库发布静态网页

### ISSUE THREAD

**Issue by ForteScarlet** [Xrysnow/TheSecondEruptionEnhancedEdition#1]
我在一个[其他仓库](https://github.com/Theater-of-Domination/TheSecondEruptionEnhancedEdition)中将 `「第二次崩坏」增强版` 的内容通过GitHub Pages发布为了[在线版](https://theater-of-domination.github.io/TheSecondEruptionEnhancedEdition/)，并且保留了所有在仓库README、漫画首页等位置的声明，包括此仓库的链接和作者等。
不知这种行为是否被允许？

**Comment by Xrysnow** [comment]
可以的🆗

**Comment by ForteScarlet** [comment]
> 可以的🆗

了解，感谢答复❤️
